name: Test

on: push

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "lala"
      - name: 2 commands
        env: 
          STEP_ENV2: env that is available only to this step
        run: |
          pwd
          ls -a
          date
          echo "STEP_ENV is ${STEP_ENV2}"
          echo $STEP_ENV2 >> testFile.txt
          ls -a

      