name: Test

on: push

jobs:
  simple-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        env: 
          STEP_ENV: available only to this step
        run: echo "lala"
      - name: 2 commands
        run: |
          pwd
          ls -a
          date
          echo "STEP_ENV is ${STEP_ENV}"

      